const itskill = [
      "JavaScript",
      "Python",
      "Java",
      "C++",
      "Ruby",
      "Swift",
      "Go",
      "Rust",
      "PHP",
      "Perl",
      "React",
      "Angular",
      "Vue.js",
      "Express",
      "Django",
      "Flask",
      "Ruby on Rails",
      "Laravel",
      "Spring",
      "Hibernate",
      "MySQL",
      "PostgreSQL",
      "MongoDB",
      "Microsoft SQL Server",
      "Oracle",
      "IBM DB2",
      "Firebase",
      "Cassandra",
      "Redis",
      "GraphQL",
      "Azure",
      "Docker",
      "Kubernetes",
      "AWS",
      "Google Cloud Platform",
      "Heroku",
      "OpenShift",
      "Cloud Foundry",
      "Pivotal Cloud Foundry",
      "IBM Cloud"

];

  export default itskill