const NATIONALITIES = {
    AFGHAN: { index: 1, name: 'Afghan', nation: 'Afghanistan' },
    ALBANIAN: { index: 2, name: 'Albanian', nation: 'Albania' },
    ALGERIAN: { index: 3, name: 'Algerian', nation: 'Algeria' },
    ANDORRAN: { index: 4, name: 'Andorran', nation: 'Andorra' },
    ANGOLAN: { index: 5, name: 'Angolan', nation: 'Angola' },
    ANTIGUAN: { index: 6, name: 'Antiguan', nation: 'Antigua and Barbuda' },
    ARGENTINE: { index: 7, name: 'Argentine', nation: 'Argentina' },
    ARMENIAN: { index: 8, name: 'Armenian', nation: 'Armenia' },
    AUSTRALIAN: { index: 9, name: 'Australian', nation: 'Australia' },
    AUSTRIAN: { index: 10, name: 'Austrian', nation: 'Austria' },
    AZERBAIJANI: { index: 11, name: 'Azerbaijani', nation: 'Azerbaijan' },
    BAHAMIAN: { index: 12, name: 'Bahamian', nation: 'Bahamas' },
    BAHRAINI: { index: 13, name: 'Bahraini', nation: 'Bahrain' },
    BANGLADESHI: { index: 14, name: 'Bangladeshi', nation: 'Bangladesh' },
    BARBADIAN: { index: 15, name: 'Barbadian', nation: 'Barbados' },
    BELARUSIAN: { index: 16, name: 'Belarusian', nation: 'Belarus' },
    BELGIAN: { index: 17, name: 'Belgian', nation: 'Belgium' },
    BELIZEAN: { index: 18, name: 'Belizean', nation: 'Belize' },
    BENINESE: { index: 19, name: 'Beninese', nation: 'Benin' },
    BHUTANESE: { index: 20, name: 'Bhutanese', nation: 'Bhutan' },
    BOLIVIAN: { index: 21, name: 'Bolivian', nation: 'Bolivia' },
    BOSNIAN: { index: 22, name: 'Bosnian', nation: 'Bosnia and Herzegovina' },
    BOTSWANAN: { index: 23, name: 'Botswana', nation: 'Botswana' },
    BRAZILIAN: { index: 24, name: 'Brazilian', nation: 'Brazil' },
    BRITISH: { index: 25, name: 'British', nation: 'United Kingdom' },
    BRUNEIAN: { index: 26, name: 'Bruneian', nation: 'Brunei' },
    BULGARIAN: { index: 27, name: 'Bulgarian', nation: 'Bulgaria' },
    BURKINABE: { index: 28, name: 'Burkinabe', nation: 'Burkina Faso' },
    BURMESE: { index: 29, name: 'Burmese', nation: 'Myanmar (Burma)' },
    BURUNDIAN: { index: 30, name: 'Burundian', nation: 'Burundi' },
    CAMBODIAN: { index: 31, name: 'Cambodian', nation: 'Cambodia' },
    CAMEROONIAN: { index: 32, name: 'Cameroonian', nation: 'Cameroon' },
    CANADIAN: { index: 33, name: 'Canadian', nation: 'Canada' },
    CENTRAL_AFRICAN: { index: 34, name: 'Central African', nation: 'Central African Republic' },
    CHADIAN: { index: 35, name: 'Chadian', nation: 'Chad' },
    CHILEAN: { index: 36, name: 'Chilean', nation: 'Chile' },
    CHINESE: { index: 37, name: 'Chinese', nation: 'China' },
    COLOMBIAN: { index: 38, name: 'Colombian', nation: 'Colombia' },
    COMORIAN: { index: 39, name: 'Comorian', nation: 'Comoros' },
    CONGOLESE: { index: 40, name: 'Congolese', nation: 'Congo (Brazzaville)' },
    COSTA_RICAN: { index: 41, name: 'Costa Rican', nation: 'Costa Rica' },
    CROATIAN: { index: 42, name: 'Croatian', nation: 'Croatia' },
    CUBAN: { index: 43, name: 'Cuban', nation: 'Cuba' },
    CYPRIOT: { index: 44, name: 'Cypriot', nation: 'Cyprus' },
    CZECH: { index: 45, name: 'Czech', nation: 'Czech Republic' },
    DANISH: { index: 46, name: 'Danish', nation: 'Denmark' },
    DJIBOUTIAN: { index: 47, name: 'Djiboutian', nation: 'Djibouti' },
    DOMINICAN: { index: 48, name: 'Dominican', nation: 'Dominican Republic' },
    DUTCH: { index: 49, name: 'Dutch', nation: 'Netherlands' },
    EAST_TIMOR: { index: 50, name: 'East Timorese', nation: 'East Timor' },
    ECUADORIAN: { index: 51, name: 'Ecuadorian', nation: 'Ecuador' },
    EGYPTIAN: { index: 52, name: 'Egyptian', nation: 'Egypt' },
    EMIRATI: { index: 53, name: 'Emirati', nation: 'United Arab Emirates' },
    EQUATORIAL_GUINEAN: { index: 54, name: 'Equatorial Guinean', nation: 'Equatorial Guinea' },
    ERITREAN: { index: 55, name: 'Eritrean', nation: 'Eritrea' },
    ESTONIAN: { index: 56, name: 'Estonian', nation: 'Estonia' },
    ETHIOPIAN: { index: 57, name: 'Ethiopian', nation: 'Ethiopia' },
    FIJIAN: { index: 58, name: 'Fijian', nation: 'Fiji' },
    FINNISH: { index: 59, name: 'Finnish', nation: 'Finland' },
    FRENCH: { index: 60, name: 'French', nation: 'France' },
    GABONESE: { index: 61, name: 'Gabonese', nation: 'Gabon' },
    GAMBIAN: { index: 62, name: 'Gambian', nation: 'Gambia' },
    GEORGIAN: { index: 63, name: 'Georgian', nation: 'Georgia' },
    GERMAN: { index: 64, name: 'German', nation: 'Germany' },
    GHANAIAN: { index: 65, name: 'Ghanaian', nation: 'Ghana' },
    GREEK: { index: 66, name: 'Greek', nation: 'Greece' },
    GRENADIAN: { index: 67, name: 'Grenadian', nation: 'Grenada' },
    GUATEMALAN: { index: 68, name: 'Guatemalan', nation: 'Guatemala' },
    GUINEAN: { index: 69, name: 'Guinean', nation: 'Guinea' },
    GUINEA_BISSAU: { index: 70, name: 'Guinea-Bissauan', nation: 'Guinea-Bissau' },
    HAITIAN: { index: 71, name: 'Haitian', nation: 'Haiti' },
    HONDURAN: { index: 72, name: 'Honduran', nation: 'Honduras' },HUNGARIAN: { index: 73, name: 'Hungarian', nation: 'Hungary' },
    ICELANDIC: { index: 74, name: 'Icelandic', nation: 'Iceland' },
    INDIAN: { index: 75, name: 'Indian', nation: 'India' },
    INDONESIAN: { index: 76, name: 'Indonesian', nation: 'Indonesia' },
    IRISH: { index: 77, name: 'Irish', nation: 'Ireland' },
    ISRAELI: { index: 78, name: 'Israeli', nation: 'Israel' },
    ITALIAN: { index: 79, name: 'Italian', nation: 'Italy' },
    IVORIAN: { index: 80, name: 'Ivorian', nation: 'Côte d\'Ivoire' },
    JAMAICAN: { index: 81, name: 'Jamaican', nation: 'Jamaica' },
    JAPANESE: { index: 82, name: 'Japanese', nation: 'Japan' },
    JORDANIAN: { index: 83, name: 'Jordanian', nation: 'Jordan' },
    KAZAKHSTANI: { index: 84, name: 'Kazakhstani', nation: 'Kazakhstan' },
    KENYAN: { index: 85, name: 'Kenyan', nation: 'Kenya' },
    KIRIBATIAN: { index: 86, name: 'Kiribatian', nation: 'Kiribati' },
    KUWAITI: { index: 87, name: 'Kuwaiti', nation: 'Kuwait' },
    KYRGYZ: { index: 88, name: 'Kyrgyz', nation: 'Kyrgyzstan' },
    LAOTIAN: { index: 89, name: 'Laotian', nation: 'Laos' },
    LATVIAN: { index: 90, name: 'Latvian', nation: 'Latvia' },
    LEBANESE: { index: 91, name: 'Lebanese', nation: 'Lebanon' },
    LESOTHO: { index: 92, name: 'Lesotho', nation: 'Lesotho' },
    LIBERIAN: { index: 93, name: 'Liberian', nation: 'Liberia' },
    LIBYAN: { index: 94, name: 'Libyan', nation: 'Libya' },
    LIECHTENSTEINER: { index: 95, name: 'Liechtensteiner', nation: 'Liechtenstein' },
    LITHUANIAN: { index: 96, name: 'Lithuanian', nation: 'Lithuania' },
    LUXEMBOURGER: { index: 97, name: 'Luxembourger', nation: 'Luxembourg' },
    MACEDONIAN: { index: 98, name: 'Macedonian', nation: 'North Macedonia' },
    MALAWIAN: { index: 99, name: 'Malawian', nation: 'Malawi' },
    MALAYSIAN: { index: 100, name: 'Malaysian', nation: 'Malaysia' },
    MALDIVIAN: { index: 101, name: 'Maldivian', nation: 'Maldives' },
    MALIAN: { index: 102, name: 'Malian', nation: 'Mali' },
    MALTESE: { index: 103, name: 'Maltese', nation: 'Malta' },
    MAROCCAN: { index: 104, name: 'Moroccan', nation: 'Morocco' },
    MARSHALLESE: { index: 105, name: 'Marshallese', nation: 'Marshall Islands' },
    MAURITANIAN: { index: 1106, name: 'Mauritanian', nation: 'Mauritania' },
    MAURITIAN: { index: 107, name: 'Mauritian', nation: 'Mauritius' },
    MEXICAN: { index: 108, name: 'Mexican', nation: 'Mexico' },
    MICRONESIAN: { index: 109, name: 'Micronesian', nation: 'Micronesia' },
    MOLDOVAN: { index: 110, name: 'Moldovan', nation: 'Moldova' },
    MONACAN: { index: 111, name: 'Monacan', nation: 'Monaco' },
    MONGOLIAN: { index: 112, name: 'Mongolian', nation: 'Mongolia' },
    MONTENEGRIN: { index: 113, name: 'Montenegrin', nation: 'Montenegro' },
    MOZAMBICAN: { index: 114, name: 'Mozambican', nation: 'Mozambique' },
    NAMIBIAN: { index: 115, name: 'Namibian', nation: 'Namibia' },
    NAURUAN: { index: 116, name: 'Nauruan', nation: 'Nauru' },
    NEPALESE: { index: 117, name: 'Nepalese', nation: 'Nepal' },
    NEW_ZEALANDER: { index: 118, name: 'New Zealander', nation: 'New Zealand' },
    NICARAGUAN: { index: 119, name: 'Nicaraguan', nation: 'Nicaragua' },
    NIGERIAN: { index: 120, name: 'Nigerian', nation: 'Nigeria' },
    NIGERIEN: { index: 121, name: 'Nigerien', nation: 'Niger' },
    NORTH_KOREAN: { index: 122, name: 'North Korean', nation: 'North Korea' },
    NORWEGIAN: { index: 123, name: 'Norwegian', nation: 'Norway' },
    OMANI: { index: 124, name: 'Omani', nation: 'Oman' },
    PAKISTANI: { index: 125, name: 'Pakistani', nation: 'Pakistan' },
    PANAMANIAN: { index: 126, name: 'Panamanian', nation: 'Panama' },
    PAPUA_NEW_GUINEAN: { index: 127, name: 'Papua New Guinean', nation: 'Papua New Guinea' },
    PARAGUAYAN: { index: 128, name: 'Paraguayan', nation: 'Paraguay' },
    PERUVIAN: { index: 129, name: 'Peruvian', nation: 'Peru' },
    PHILIPPINE: { index: 130, name: 'Philippine', nation: 'Philippines' },
    POLISH: { index: 131, name: 'Polish', nation: 'Poland' },
    PORTUGUESE: { index: 132, name: 'Portuguese', nation: 'Portugal' },
    QATARI: { index: 133, name: 'Qatari', nation: 'Qatar' },
    ROMANIAN: { index: 134, name: 'Romanian', nation: 'Romania' },
    RUSSIAN: { index: 135, name: 'Russian', nation: 'Russia' },
    RWANDAN: { index: 136, name: 'Rwandan', nation: 'Rwanda' },
    SAINT_LUCIAN: { index: 137, name: 'Saint Lucian', nation: 'Saint Lucia' },
    SALVADORAN: { index: 138, name: 'Salvadoran',nation: 'El Salvador' },
    SAMOAN: { index: 139, name: 'Samoan', nation: 'Samoa' },
    SAN_MARINO: { index: 140, name: 'San Marino', nation: 'San Marino' },
    SÃO_TOMEAN: { index: 141, name: 'São Toméan', nation: 'São Tomé and Príncipe' },
    SAUDI_ARABIAN: { index: 142, name: 'Saudi Arabian', nation: 'Saudi Arabia' },
    SCOTTISH: { index: 143, name: 'Scottish', nation: 'Scotland' },
    SENEGALESE: { index: 144, name: 'Senegalese', nation: 'Senegal' },
    SERBIAN: { index: 145, name: 'Serbian', nation: 'Serbia' },
    SEYCHELLOIS: { index: 146, name: 'Seychellois', nation: 'Seychelles' },
    SIERRA_LEONEAN: { index: 147, name: 'Sierra Leonean', nation: 'Sierra Leone' },
    SINGAPOREAN: { index: 148, name: 'Singaporean', nation: 'Singapore' },
    SLOVAK: { index: 149, name: 'Slovak', nation: 'Slovakia' },
    SLOVENIAN: { index: 150, name: 'Slovenian', nation: 'Slovenia' },
    SOLOMON_ISLANDER: { index: 151, name: 'Solomon Islander', nation: 'Solomon Islands' },
    SOMALI: { index: 152, name: 'Somali', nation: 'Somalia' },
    SOUTH_AFRICAN: { index: 153, name: 'South African', nation: 'South Africa' },
    SOUTH_KOREAN: { index: 154, name: 'South Korean', nation: 'South Korea' },
    SPANISH: { index: 155, name: 'Spanish', nation: 'Spain' },
    SRI_LANKAN: { index: 156, name: 'Sri Lankan', nation: 'Sri Lanka' },
    SUDANESE: { index: 157, name: 'Sudanese', nation: 'Sudan' },
    SURINAMER: { index: 158, name: 'Surinamer', nation: 'Suriname' },
    SWAZI: { index: 159, name: 'Swazi', nation: 'Swaziland' },
    SWEDISH: { index: 160, name: 'Swedish', nation: 'Sweden' },
    SWISS: { index: 161, name: 'Swiss', nation: 'Switzerland' },
    SYRIAN: { index: 162, name: 'Syrian', nation: 'Syria' },
    TAJIK: { index: 163, name: 'Tajik', nation: 'Tajikistan' },
    TANZANIAN: { index: 164, name: 'Tanzanian', nation: 'Tanzania' },
    THAI: { index: 165, name: 'Thai', nation: 'Thailand' },
    TIMORESE: { index: 166, name: 'Timorese', nation: 'Timor-Leste' },
    TOGOLESE: { index: 167, name: 'Togolese', nation: 'Togo' },
    TONGAN: { index: 168, name: 'Tongan', nation: 'Tonga' },
    TRINIDADIAN_AND_TOBAGONIAN: { index: 169, name: 'Trinidadian and Tobagonian', nation: 'Trinidad and Tobago' },
    TUNISIAN: { index: 170, name: 'Tunisian', nation: 'Tunisia' },
    TURKISH: { index: 171, name: 'Turkish', nation: 'Turkey' },
    TURKMEN: { index: 172, name: 'Turkmen', nation: 'Turkmenistan' },
    TUVALUAN: { index: 173, name: 'Tuvaluan', nation: 'Tuvalu' },
    UGANDAN: { index: 174, name: 'Ugandan', nation: 'Uganda' },
    UKRAINIAN: { index: 175, name: 'Ukrainian', nation: 'Ukraine' },
    URUGUAYAN: { index: 176, name: 'Uruguayan', nation: 'Uruguay' },
    UZBEK: { index: 177, name: 'Uzbek', nation: 'Uzbekistan' },
    VANUATUAN: { index: 178, name: 'Vanuatuan', nation: 'Vanuatu' },
    VATICAN_CITY: { index: 179, name: 'Vatican City', nation: 'Vatican City' },
    VENEZUELAN: { index: 180, name: 'Venezuelan', nation: 'Venezuela' },
    VIETNAMESE: { index: 181, name: 'Vietnamese', nation: 'Vietnam' },
    WESTERN_SAHARAN: { index: 182, name: 'Western Saharan', nation: 'Western Sahara' },
    YEMENI: { index: 183, name: 'Yemeni', nation: 'Yemen' },
    ZAMBIAN: { index: 184, name: 'Zambian', nation: 'Zambia' },
    ZIMBABWEAN: { index: 185, name: 'Zimbabwean', nation: 'Zimbabwe' },
    ZOMBIAN: { index: 186, name: 'Zombie', nation: 'The Living Dead' }
  };

  export default NATIONALITIES
  